### ISSUE TITLE
Method name homogenization

### ISSUE THREAD

**Issue by anjos** [idiap/bob#140]
> This was one of the issues of #104 that was dettached and moved here.

The library is becoming larger. We should have stricter rule when defining class methods that refers to the same concept. For instance, very often, we have a variable related to the input/feature dimensionality. Depending on the class, it might be obtained using a 'getDimD()', 'inputDims()', or whatsoever. I think this is very annoying from a user perspective. Same for the API of the trainers.

**Comment by tiagofrepereira2012** [comment]
Already done for the packages in bob 2.0
