### ISSUE TITLE
./bin/buildout , then where this installed to ?

### ISSUE THREAD

**Issue by StevenLOL** [idiap/bob#197]
Follow your readme till

./bin/buildout 

then  where this installed to ?

**Comment by StevenLOL** [comment]
The best way to install bob is from 

sudo pip install .....

**Comment by siebenkopf** [comment]
To answer your first question: when you use bin/buildout, the packages get installed into the eggs/ directory, local in your current path. To have a global installation of the bob packages, indeed, the pip install command works better. Unfortunately, with pip install, you need to install packages in the right order, i.e., to fulfill dependencies. A good (e.g. graphical) list of dependencies for all packages is still missing, but we will work on that.

Additionally, we have lately found an issue with buildout. It seems that zc.buildout and setuptools have updated their versions, which are currently incompatible with the version in our Bob packages, and I am not sure that the one linked in the Wiki still works perfectly. We will update the information as soon as the zc.buildout/setuptools combination is stable again.
