### ISSUE TITLE
"No distribution at all found for bob>1.1.0" for Antispoofing.motion and antispoofing.optflow

### ISSUE THREAD

**Issue by devrim108** [idiap/bob#199]
Hi,

I installed all dependencies and all bob packages using pip on Ubuntu 14.04.1 LTS 64 bit system. Afterward i wanted to install antispoofing.motion and antispoofing.optflow. I got an error;

Could not find  any downloads that satisfy the requirement bob>=1.1.0 (from antispoofing.optflow)
Cleaning up...
No distributions at all found for bob>=1.1.0 (from antispoofing.optflow)
Storing debug log for failure in /home/ubuntu/.pip/pip.log

**Comment by anjos** [comment]
Thanks for this report. Please follow-up my answer on the development mailing list.

**Comment by devrim108** [comment]
Thanks for your information. i am applying your steps.
