### ISSUE TITLE
Not able to install bob nor antispoofing.lbptop on both Mac OS X 8.x

### ISSUE THREAD

**Issue by StevenLobo2** [idiap/bob#200]
Nothing is installed if I do pip install bob. 
So I started following instructions given in https://github.com/idiap/bob/wiki/Installation. I was able to install bob.extension, core. But there were two errors for bob.io.base. 
error: duplicate case value 'NPY_ULONGLONG'

    case NPY_ULONGLONG:

But if I do import bob and print bob.version. Nothing gets printed. How to install bob basic library required for antispoofing.lbptop. 

I am not able to install on Centos also. Is there any rpm for centOS.

If I try to install antispoofing.lbptop, I am getting bob >1… not found.
Thanks
Steven

**Comment by siebenkopf** [comment]
antispoofing.lbptop requires Bob 1, which is not compatible with Bob 2. The installation instructions that you found under the link  https://github.com/idiap/bob/wiki/Installation is valid only for Bob 2.
Bob 1 needs a full installation of a single monolithic package ("bob"), while the Bob 2 is split into packages, so that a package called "bob" for version 2 does not exist any more. Hence, 'bob.version' is not a valid query for Bob 2.

@anjos: Do we have the installation instructions for Bob 1 somewhere? In the wiki I couldn't find them...

This means that you don't need the bob.core, ... packages to run antispoofing.lbptop. However, the error that you is new for me. Could you please post more detailed information (compiler version, system version (32 or 64 bit), and the full error trace) so that we can try to solve this issue?

Manuel

**Comment by StevenLobo2** [comment]
Thanks a lot for the information. I also tried to install bob 1.2. But I am getting error "Linking CXX shared library ../../../lib/libbob_visioner.dylib"(after 82 %) undefined symbols for architecture x86_64:
  "boost::thread::start_thread()", referenced from:…………..
As per different internet sources I need to update makeFile to use -lboost_thread-mt while compilation. But I am not able to figure out where all libraries are included for compilation. 

src/visioner/cxx/CMakeFiles/bob_visioner.dir/build.make already includes "lib/libbob_visioner.dylib: /usr/local/lib/libboost_thread-mt.dylib" I also have boost library installed from brew.

**Comment by anjos** [comment]
There is currently an incompatibility with Bob on OS X: https://trac.macports.org/ticket/46441#comment:8

I have submitted a patch, but that seems ignored. I've pinged the responsible parties @ MacPorts so, let's wait a bit to see that fixed properly.

If you want to compile and install Bob v1 locally, please use the patch described in that bug to patch the latest Portfile for Bob and port-install manually. You can find instructions on how to do it here: https://github.com/idiap/bob.mac/blob/master/ports/README.md. I'd still recommend you wait for the official patch, as that simplifies things. Nevertheless, if you're in a hurry, you can try this other installation method and later updated it properly.

**Comment by StevenLobo2** [comment]
Thank you very much. Is there any simple way to install it on RHEL 6.5. I want to install antispoofing.lbptop on RHEL 6.5 which requires Bob1.2 and above. The instructions are available only for ubuntu with apt-get. Is there anyway to install using yum? It would be great if you can provide me the details for RHEL. Since I didn't find any rpm for blitz/bob on RHEL so  I tried it on Mac.

**Comment by anjos** [comment]
Hello,

There are no RPMs for Bob v1 yet. We have started to do some work on it a year ago, but then it got halted. We're always looking for interested parties in taking it over and maintaining it.

If you're interested, please have a look here: https://github.com/bioidiap/bob.rpm

**Comment by StevenLobo2** [comment]
Thanks Anjos. I followed the link. But now on CentOS 6 the build fails at blitz API's. I have installed blitz-devel using yum install. The cmake configuration shows below messages for blitz. This issue is not seen Mac OS X.( here I get path for tinyvec2.h) Is there specific version/settings  for blitz to be installed. 

"-- Performing Test HAVE_BLITZ_SPECIAL_TYPES
-- Performing Test HAVE_BLITZ_SPECIAL_TYPES - Failed
-- Found Blitz++: blitz (>2G-pointees: ; New: HAVE_BLITZ_TINYVEC2_H-NOTFOUND)
"

**Comment by anjos** [comment]
What is the version of Blitz++ installed on your machine? You need 0.10.

Let's please move this discussion @ our mailing list. It makes more sense. I'll close this bug.

**Comment by thebunpit** [comment]
I'm having the same problem (duplicate case value 'NPY_ULONGLONG') error on Mac OS X. Was the issue resolved? Thanks!

**Comment by anjos** [comment]
I think this was solved. Please have a look at our mailing list.

**Comment by thebunpit** [comment]
Do you have a link to the discussion? I was unable to find it. I am having the same error running pip install bob.io.base:

bob/io/base/hdf5.cpp:349:10: error: duplicate case value 'NPY_LONGLONG'
        case NPY_LONGLONG:
             ^
    bob/io/base/hdf5.cpp:333:10: note: previous case defined here
        case NPY_INT64:      return bob::io::base::i64;
             ^
    /System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/numpy/core/include/numpy/npy_common.h:332:23: note: expanded from macro 'NPY_INT64'
    #    define NPY_INT64 NPY_LONGLONG
                          ^
    bob/io/base/hdf5.cpp:358:10: error: duplicate case value 'NPY_ULONGLONG'
        case NPY_ULONGLONG:
             ^
    bob/io/base/hdf5.cpp:337:10: note: previous case defined here
        case NPY_UINT64:     return bob::io::base::u64;
             ^
    /System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/numpy/core/include/numpy/npy_common.h:333:24: note: expanded from macro 'NPY_UINT64'
    #    define NPY_UINT64 NPY_ULONGLONG
                           ^
    bob/io/base/hdf5.cpp:661:51: warning: implicit conversion loses integer precision: 'const hsize_t' (aka 'const unsigned long long') to 'npy_intp' (aka 'long') [-Wshorten-64-to-32]
      for (size_t k=0; k<shape.n(); ++k) pyshape[k] = shape.get()[k];
                                                    ~ ^~~~~~~~~~~~~~
    bob/io/base/hdf5.cpp:729:58: warning: implicit conversion loses integer precision: 'uint64_t' (aka 'unsigned long long') to 'int' [-Wshorten-64-to-32]
        PyObject* item = PyBobIoHDF5File_Xread(self, key, 0, k);
                         ~~~~~~~~~~~~~~~~~~~~~               ^
    bob/io/base/hdf5.cpp:1492:51: warning: implicit conversion loses integer precision: 'const hsize_t' (aka 'const unsigned long long') to 'npy_intp' (aka 'long') [-Wshorten-64-to-32]
      for (size_t k=0; k<shape.n(); ++k) pyshape[k] = shape.get()[k];
                                                    ~ ^~~~~~~~~~~~~~
    3 warnings and 2 errors generated.
    error: command 'cc' failed with exit status 1

**Comment by anjos** [comment]
OK, I was mistaken - it was another thread on another subject.

Could you please specify which version of Mac OSX and MacPorts you're using?

**Comment by thebunpit** [comment]
I get this error when I try installing with pip. I'm using Mac OSX 10.9.5, pip 7.0.3, and MacPorts 2.3.3

**Comment by anjos** [comment]
How are you pip installing everything? Did you follow our guide?

**Comment by thebunpit** [comment]
I'm running pip install ____
I was able to install everything in the guide up to bob.core, I started getting errors when I tried pip install bob.io.base.

**Comment by anjos** [comment]
Could you check the following?

```sh
$ which pip
/opt/local/bin/pip-2.7
$ which python
/opt/local/bin/python
$ port select --list python
...
python27 (active)
...
```

**Comment by thebunpit** [comment]
Hm, I get
```
ATMHUANGB01:facereclib-2.1.0 huangb$ which pip
/usr/local/bin/pip
ATMHUANGB01:facereclib-2.1.0 huangb$ which python
/usr/bin/python
ATMHUANGB01:facereclib-2.1.0 huangb$ port select --list python
Available versions for python:
	none (active)
	python25-apple
	python26-apple
	python27
	python27-apple
```
I'm guessing that's the problem

**Comment by anjos** [comment]
Please make sure you read our system setup guide for OSX: https://github.com/idiap/bob/wiki/Dependencies#mac-osx-with-macports

**Comment by anjos** [comment]
Also, please first discuss problems like this through our mailing list. This bug is closed.
