### ISSUE TITLE
How to Install bob on Mac Yosemite 10.10.2

### ISSUE THREAD

**Issue by SteveK2** [idiap/bob#201]
Why do I get this error:
Steves-Mac-mini:bob.spear-1.1.8 steve$ ./bin/buildout 
Develop: '/Users/steve/Desktop/work/bob.spear-1.1.8/.'
Installing scripts.
Getting distribution for 'bob>=1.2.0'.
While:
  Installing scripts.
  Getting distribution for 'bob>=1.2.0'.
Error: Couldn't find a distribution for 'bob>=1.2.0'.

mac port says bob 1.2.2 is installed:
Steves-Mac-mini:bob.spear-1.1.8 steve$ port installed bob
The following ports are currently installed:
  bob @1.2.2_8+python27 (active)

Are there consistent/complete installation instructions for installing/testing on a Mac?

**Comment by anjos** [comment]
This problem is covered on our wiki: https://github.com/idiap/bob/wiki/Dependencies#mac-osx-with-macports. Please have a look.

That info is valid for Bob v1 or Bob v2.

**Comment by SteveK2** [comment]
hmm... ran those installs (even correcting errors from outdated module names), but still no luck.
Guess I'm missing something. Sorry for my lack of understanding of your build system.

Steves-Mac-mini:bob.spear-1.1.8 steve$ ls
COPYING			bin			buildout.cfg		hide			setup.cfg
MANIFEST.in		bob.spear.egg-info	config			icassp_2014		setup.py
PKG-INFO		bootstrap-buildout.py	develop-eggs		parts			spear
README.rst		bootstrap.py		eggs			protocols
Steves-Mac-mini:bob.spear-1.1.8 steve$ ./bin/buildout 
Develop: '/Users/steve/Desktop/work/bob.spear-1.1.8/.'
Installing scripts.
Getting distribution for 'bob>=1.2.0'.
While:
  Installing scripts.
  Getting distribution for 'bob>=1.2.0'.
Error: Couldn't find a distribution for 'bob>=1.2.0'.
Steves-Mac-mini:bob.spear-1.1.8 steve$ port installed bob
The following ports are currently installed:
  bob @1.2.2_8+python27 (active)


1) Do you run nightly or weekly test builds of your platform on a scratch Mac?
2) Can you provide the scripts used to build, install, and test run the software on a Mac?
3) Can you provide the complete logs of the installation and test so that one may compare results to help identify problem areas.

**Comment by anjos** [comment]
Please state what is:

```sh
$ which python
```

And report it back

**Comment by anjos** [comment]
Also try:

```sh
$ port select --list python
```

**Comment by SteveK2** [comment]
Steves-Mac-mini:bob.spear-1.1.8 steve$ which python
/usr/bin/python

Steves-Mac-mini:bob.spear-1.1.8 steve$ port select --list python
Available versions for python:
	none (active)
	python26-apple
	python27
	python27-apple

**Comment by anjos** [comment]
Have you read this **carefully**? (link from above)

https://github.com/idiap/bob/wiki/Dependencies#mac-osx-with-macports.
