### ISSUE TITLE
when I run ./bin/buildout, encounter errors

### ISSUE THREAD

**Issue by xuzhenqi** [idiap/bob#202]
pris@pris-All-Series:~/development/bob$ ./bin/buildout 
Develop: '/home/pris/development/bob/layers/0/bob.buildout'
Traceback (most recent call last):
  File "/tmp/tmpeiOSwz", line 14, in <module>
    exec(compile(open('/home/pris/development/bob/layers/0/bob.buildout/setup.py').read(), '/home/pris/development/bob/layers/0/bob.buildout/setup.py', 'exec'))
IOError: [Errno 2] No such file or directory: '/home/pris/development/bob/layers/0/bob.buildout/setup.py'
While:
  Installing.
  Processing develop directory '/home/pris/development/bob/layers/0/bob.buildout'.

An internal error occurred due to a bug in either zc.buildout or in a
recipe being used:
Traceback (most recent call last):
  File "/home/pris/development/bob/eggs/zc.buildout-2.3.1-py2.7.egg/zc/buildout/buildout.py", line 1946, in main
    getattr(buildout, command)(args)
  File "/home/pris/development/bob/eggs/zc.buildout-2.3.1-py2.7.egg/zc/buildout/buildout.py", line 488, in install
    installed_develop_eggs = self._develop()
  File "/home/pris/development/bob/eggs/zc.buildout-2.3.1-py2.7.egg/zc/buildout/buildout.py", line 730, in _develop
    zc.buildout.easy_install.develop(setup, dest)
  File "/home/pris/development/bob/eggs/bob.buildout-2.0.6-py2.7.egg/bob/buildout/extension.py", line 212, in develop
    zc.buildout.easy_install.call_subprocess(args)
  File "/home/pris/development/bob/eggs/zc.buildout-2.3.1-py2.7.egg/zc/buildout/easy_install.py", line 159, in call_subprocess
    % repr(args)[1:-1])
Exception: Failed to run command:
'/usr/bin/python', '/tmp/tmpeiOSwz', '-v', 'develop', '-mxN', '-d', '/home/pris/development/bob/develop-eggs/tmprqYAaxbuild'

**Comment by anjos** [comment]
On Thu, Apr 23, 2015 at 6:06 AM, xuzhenqi <notifications@github.com> wrote:

> IOError: [Errno 2] No such file or directory:
> '/home/pris/development/bob/layers/0/bob.buildout/setup.py'
>

I'm guessing you miss:

$ git submodule init
$ git submodule update

To then be able to do:

$ ./bin/buildout

André


-- 
Dr. André Anjos
Idiap Research Institute
Centre du Parc - rue Marconi 19
CH-1920 Martigny, Suisse
Phone: +41 27 721 7763
Fax: +41 27 721 7712
http://andreanjos.org

**Comment by xuzhenqi** [comment]
Thanks！
I've done like you said. But when I run 

import bob 

in a python interpreter, I got nothing.
How to config the bob module into my python environment?

**Comment by anjos** [comment]
If the build ran w/o problems, then you must use the "python" interpreter
inside the "bin" directory:

./bin/python
...
>>> import bob

Should work. With bob v2, this will not get you much, since all the magic
now lives in submodules.

If you want, for example, to import our HDF5 I/O support, you must

import bob.io.base

# use it
bob.io.base.HDF5File(...)

André

PS: For these kind of technical questions which are non-bugs, please use
our mailing list bob-devel at Google Groups.


On Thu, Apr 23, 2015 at 9:39 AM, xuzhenqi <notifications@github.com> wrote:

> Thanks！
> I've done like you said. But when I run
>
> import bob
>
> in a python interpreter, I got nothing.
> How to config the bob module into my python environment?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/idiap/bob/issues/202#issuecomment-95478400>.
>



-- 
André Anjos
http://andreanjos.org
