### ISSUE TITLE
Matplotlib configuration

### ISSUE THREAD

**Issue by guillaume-heusch** [idiap/bob#207]
Hi guys,

It seems that matplotlib configuration has a problem .. As soon as I import matplotlib, I have the following warning: 

/idiap/group/torch5spro/releases/bob-stable/py27/local/lib/python2.7/site-packages/matplotlib/__init__.py:1039: UserWarning: Bad val "pyside" on line #38
	"backend      : pyside
"
	in file "/idiap/group/torch5spro/releases/bob-stable/py27/local/lib/python2.7/site-packages/matplotlib/mpl-data/matplotlibrc"
	Key backend: Unrecognized backend string "pyside": valid strings are [u'pgf', u'cairo', u'MacOSX', u'CocoaAgg', u'gdk', u'ps', u'GTKAgg', u'nbAgg', u'GTK', u'Qt5Agg', u'template', u'emf', u'GTK3Cairo', u'GTK3Agg', u'WX', u'Qt4Agg', u'TkAgg', u'agg', u'svg', u'GTKCairo', u'WXAgg', u'WebAgg', u'pdf']
  (val, error_details, msg))

No idea on how to solve that ...
Thanks

Guillaume

**Comment by anjos** [comment]
This comes from the fact Tiago built that release on his own computer, which does not have the qt4-devel libraries installed (I cannot overwrite it since Tiago did not make the directory group writeable.) As a consequence, Matplotlib defaults to pyside, which is also not available. The way to fix this is to ask Tiago to:

1. Ask sys admins to install qt4-development files (or better, our bob metapackage, called `custom-packages-install-project-bob`)
2. Re-run the matplotlib installation on that directory (one does not have to re-run the whole build again).

**Comment by tiagofrepereira2012** [comment]
Hi,

Sorry for the inconvenience.

For the moment I changed the symbolic link to the 30-06-2015 release.
I will be back tomorrow afternoon and I'll fix this.

Again, sorry for the inconvenience.

Tiago


On Mon, Sep 14, 2015 at 10:38 AM, André Anjos <notifications@github.com>
wrote:

> This comes from the fact Tiago built that release on his own computer,
> which does not have the qt4-devel libraries installed (I cannot overwrite
> it since Tiago did not make the directory group writeable.) As a
> consequence, Matplotlib defaults to pyside, which is also not available.
> The way to fix this is to ask Tiago to:
>
>    1. Ask sys admins to install qt4-development files (or better, our bob
>    metapackage, called custom-packages-install-project-bob)
>    2. Re-run the matplotlib installation on that directory (one does not
>    have to re-run the whole build again).
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/idiap/bob/issues/207#issuecomment-140101122>.
>



-- 
Tiago

**Comment by tiagofrepereira2012** [comment]
Hey,

The problem was fixed.

Now the ```bob-stable``` directory is linked to the ```bob-stable-2015-09-09``` build, so I will close this issue.
Any problem, just reopen it.

Sorry for the inconvenience
