### ISSUE TITLE
Troubles while installing bob.bio.spear

### ISSUE THREAD

**Issue by kometa-triatlon** [idiap/bob#208]
Hi,

I am trying to install bob.bio.spear package on Ubuntu 14.04 according to your guidelines.
First, I have successfully installed all the dependencies:

$ sudo add-apt-repository ppa:biometrics/bob
$ sudo apt-get update
$ sudo apt-get install wget git-core pkg-config cmake python-dev python-support liblapack-dev libatlas-base-dev libblitz1-dev libavformat-dev libavcodec-dev libswscale-dev libboost-all-dev libmatio-dev libjpeg8-dev libnetpbm10-dev libpng12-dev libtiff4-dev libgif-dev libhdf5-serial-dev libfftw3-dev texlive-latex-recommended texlive-latex-extra texlive-fonts-recommended libsvm-dev libvl-dev dvipng python-numpy python-scipy dvipng libopencv-dev

The, I downloaded bootstrap-buildout.py from https://bootstrap.pypa.io
Contents of buildout.cfg:
[buildout]
parts = scripts
extensions = bob.buildout
eggs = bob.bio.spear

; options for bob.buildout

[scripts]
recipe = bob.buildout:scripts
dependent-scripts = true

Here I had to remove some boolean flags because I was getting error messages like this one:
While:
  Initializing.
Error: Invalid value for 'newest' option: 'false ; to avoid re-installing new versions of packages'

Finally, I managed to create and start bin/buildout. 
However, I started getting the following error messages from linker:

Despite that, installation continued. But it has ended  with an error:

Got mock 1.3.0.
Getting distribution for 'funcsigs'.
Got funcsigs 0.4.
While:
  Installing scripts.
  Getting distribution for 'bob.bio.spear'.
  Getting distribution for 'bob.measure'.
Error: There is a version conflict.
We already have: six 1.5.2
but mock 1.3.0 requires 'six>=1.7'.

Could you please assist me in installation? Why am I getting errors, while following your installation recipes?

**Comment by siebenkopf** [comment]
To answer your second question first: Obviously, you have an older global installation of the six package, where the ``mock`` packager requires a newer version. You should update that package globally:

```
pip install --upgrade six
```

There might be more package, for which you have to do that.
@anjos Maybe we should write this somewhere in our installation instructions.

The first question seems to be an inconsistency with some python versions, Some of them don't like the comment ``; to avoid re-installing new versions of packages`` being written after the option ``false``. We should update this in the installation instructions. For you, just removing the comment should do the trick.

Manuel

**Comment by kometa-triatlon** [comment]
Thank you very much, now I have everything installed!
