### ISSUE TITLE
Add support to python 3.5 on Travis

### ISSUE THREAD

**Issue by tiagofrepereira2012** [idiap/bob#209]
Python 3.5 was released on September.
We should consider to add the support to this python version in Travis-CI.

Cheers

Tiago

**Comment by tiagofrepereira2012** [comment]
Can we close this one, since @pkorshunov did this modification ?

Cheers

**Comment by anjos** [comment]
Yes, I think so.

**Comment by pkorshunov** [comment]
I think yes. Python 3.5 is added for packages from bob.nightlies (and python 2.6 is removed).
