### ISSUE TITLE
In ``PyObject* create_module`` deleting the module in error cases causes a crash

### ISSUE THREAD

**Issue by siebenkopf** [idiap/bob#211]
In all of our C++/python bindings, we are creating a module using:

```
# if PY_VERSION_HEX >= 0x03000000
  PyObject* m = PyModule_Create(&module_definition);
# else
  PyObject* m = Py_InitModule3(BOB_EXT_MODULE_NAME, module_methods, module_docstr);
# endif
  if (!m) return 0;
  auto m_ = make_safe(m); ///< protects against early returns
```

At least for Python 2 (the ``Py_InitModule3`` case), doing the ``make_safe(m)`` is not a good idea, since in error cases (e.g. when an import of an external module fails later), the ``m`` object will be destroyed. Apparently, it seems that Python keeps track of the modules internally. Hence, it will try to destroy the module itself, which will fail since it is already destroyed.

A simple example could work as follows:

```
static PyObject* create_module (void) {

# if PY_VERSION_HEX >= 0x03000000
  PyObject* m = PyModule_Create(&module_definition);
# else
  PyObject* m = Py_InitModule3(BOB_EXT_MODULE_NAME, module_methods, module_docstr);
# endif
  if (!m) return 0;
  auto m_ = make_safe(m);  /// THIS IS THE PROBLEM

  PyErr_Format(PyExc_ImportError, "Bla"); /// SIGNALS AN ERROR
  return 0;
}

PyMODINIT_FUNC BOB_EXT_ENTRY_NAME (void) {
# if PY_VERSION_HEX >= 0x03000000
  return
# endif
    create_module();
}
```

If you compile this code, and try to import the module, different things might happen. Sometimes you see the ``ImportError: Bla`` message, but not always. Sometimes you also get ``Fatal Python error: Inconsistent interned string state.`` For sure, at the latest after you close the interpreter, you will observe an ``Aborted (core dumped)``.

This will affect basically all of our bindings. Yet, I am not sure, if we also need to change the code for Python3 (the ``PyModule_Create`` case above), or if we there need to destroy the module in error cases. I will investigate.

**Comment by siebenkopf** [comment]
Update: For Pyhton3, the ``make_safe`` is required, at least it doesn't harm. So, we have to find a solution that works for both. I would suggest, the easiest is:

```
static PyObject* create_module (void) {

# if PY_VERSION_HEX >= 0x03000000
  PyObject* m = PyModule_Create(&module_definition);
  auto m_ = make_xsafe(m);
  const char* ret = "O";
# else
  PyObject* m = Py_InitModule3(BOB_EXT_MODULE_NAME, module_methods, module_docstr);
  const char* ret = "N";
# endif
  if (!m) return 0;
  ...
  return Py_BuildValue(ret, m);
}

PyMODINIT_FUNC BOB_EXT_ENTRY_NAME (void) {
# if PY_VERSION_HEX >= 0x03000000
  return
# endif
    create_module();
}
```

I have tested this code for all error and success cases for both Python2 and Python3. In error cases, it will successfully write the error (``ImportError: Bla`` in the example above), and not crash the interpreter. And, in cases of success, it will not create a memory leak.

I am afraid, that we have to go on and implement this modification in all packages that contain C++ bindings. Be aware that there are usually some cases per module, where this needs to be done (usually in the ``main.cpp`` and in the ``version.cpp``).

**Comment by anjos** [comment]
Thanks for this update. It would be faster and more error-free if you made the changes and commited the packages (at least on bob.nightlies packages)

**Comment by siebenkopf** [comment]
I think I changed it for all packages. It should work as expected now. Hence, I close this bug.

I have also updated the examples in ``bob.extension`` to use this module creation. Hence, new packages  (that are based on ``bob.extension``'s examples) should work fine. Please also check your existing own ``C++/Python`` packages.
