### ISSUE TITLE
local and global import of bob modules not possible

### ISSUE THREAD

**Issue by siebenkopf** [idiap/bob#212]
I am afraid to say that the namespace issue inside bob still seems to be unsolved, at least partially. I just want to verify with you guys that you can reproduce the following issue.

Assume that you have a script ``example.py`` like follows:
```
import bob.io.base

def main():
  # use bob.io.base
  h = bob.io.base.HDF5File("xxx.hdf5", 'w')
  # import another bob module
  import bob.ip.base

if __name__ == '__main__':
  main()
```

Now, when I try to execute that script (given that I have the according bob modules installed in my python path):
```
$ python example.py
...
UnboundLocalError: local variable 'bob' referenced before assignment
```

I have traced the issue down to the fact that I am ``import``ing one of the ``bob`` modules after I use another one. When I import both in the beginning of the file, or before I use them the first time, everything is fine. Even if I do a relative import later (e.g., ``from bob.ip.base import LBP``) it works.

I am not sure if this is intended behavior, or if other modules have the same issue. Maybe it has something to do with the fact that the ``site`` package hack, which we have introduced earlier into ``bob.buildout`` to make it work with the old namespace issue, is still in the code?

**Comment by anjos** [comment]
This looks like a Python issue, but not sure. Have you scanned the net for an answer?

**Comment by siebenkopf** [comment]
No, I haven't tried to find a solution yet. I am just pretty sure that with the old version of the namespace handling, the above code was working fine. So, I assume that it has something to do with the switch ``setuptools`` -> ``pkgutil`` in the ``__init__.py`` files.

**Comment by tiagofrepereira2012** [comment]
Hi Manuel,

Just to compliment the post, I just run your script with an old stable
release (with the old namespace package handling) and it crashes in the
same way.

Cheers

On Wed, Feb 3, 2016 at 10:25 PM, Manuel Günther (aka. Gunther, Guenther) <
notifications@github.com> wrote:

> No, I haven't tried to find a solution yet. I am just pretty sure that
> with the old version of the namespace handling, the above code was working
> fine. So, I assume that it has something to do with the switch setuptools
> -> pkgutil in the __init__.py files.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/idiap/bob/issues/212#issuecomment-179478025>.
>



-- 
Tiago

**Comment by anjos** [comment]
This indicates the problem is elsewhere.

**Comment by 183amir** [comment]
@siebenkopf You are getting an error because python thinks your `bob` is a local variable. https://docs.python.org/3/faq/programming.html#why-am-i-getting-an-unboundlocalerror-when-the-variable-has-a-value
You can try adding `global bob` at the beginning of your main function and it should work.

**Comment by siebenkopf** [comment]
Yes, adding ``global bob`` inside ``main()`` in the example above works. Thank's!
