### ISSUE TITLE
Using Bob at Idiap

### ISSUE THREAD

**Issue by 183amir** [idiap/bob#213]
The Wiki page is outdated and does not work.
https://github.com/idiap/bob/wiki/Using-Bob-at-Idiap
Where can I find the latest documentation?

**Comment by anjos** [comment]
Hello. Welcome to the team and thanks for reporting this issue.

The best way to get in touch with everyone is to use our mailing list:

https://groups.google.com/forum/?fromgroups#!forum/bob-devel

I have updated the wiki page:

https://github.com/idiap/bob/wiki/Using-Bob-at-Idiap

It should work now.
