### ISSUE TITLE
Licensing mismatch in setup.py

### ISSUE THREAD

**Issue by ju55i** [idiap/bob#214]
Setup.py has a license set as GPL 3 but the classifiers has BSD. Which one is the correct one?

**Comment by anjos** [comment]
Bob is licensed under BSD. We'll fix that. Thanks for reporting.

**Comment by ju55i** [comment]
This issue should remain open until the file has actually been changed.

**Comment by tiagofrepereira2012** [comment]
Just updated the licence.

A new version of bob on pypi will be released soon.
Thanks for the report.
