### ISSUE TITLE
Usage of LBP class from bob.ip.base

### ISSUE THREAD

**Issue by marianapbento** [idiap/bob#222]
Hello,

I want to extract the local binary patters from 3D images on python, and found that bob API presents a LBP class, but the input image must be 2D. However, this class presents as one of the input parameters the number of neighbors (that might be 4,8 or 16). My question is: how a 16-neighbood is defined on 2d images? Is it possible to use LBPTop to computed a LBP from a 3d image?

Thanks in advance.

**Comment by anjos** [comment]
Thanks for your interest. Could you please post these questions on our dev mailing list?

https://groups.google.com/forum/?fromgroups#!forum/bob-devel

**Comment by marianapbento** [comment]
Sure! thanks!
