### ISSUE TITLE
Links to Youtube videos on Starter Course page are dead

### ISSUE THREAD

**Issue by pkorshunov** [idiap/bob#224]
Links to youtube videos on this page lead to dead videos:
https://github.com/idiap/bob/wiki/Bob-starter-course
Here are the dead links:
* Motivation - [Introduction to the Course](http://www.youtube.com/watch?v=XjuXOrrWAcA)
* Part I - [Introduction to Python](http://www.youtube.com/watch?v=HpdhwfD9gTw)
* Part II - [Introduction to Bob](http://www.youtube.com/watch?v=yErzyxOY4nY)
* Part III - [Advanced Topics](http://www.youtube.com/watch?v=AH9AQTMSI_w)

**Comment by siebenkopf** [comment]
Maybe we should remove this page altogether, as this is using the outdated version bob 1.

**Comment by 183amir** [comment]
I saw some people actually reading that page and using bob from the virtualbox provided.

**Comment by anjos** [comment]
The links are updated now.

**Comment by pkorshunov** [comment]
works for me now, thank you!
